services:
  - type: web
    name: telegram-video-bot
    runtime: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_BOT_TOKEN
    pythonVersion: 3.11.9
